galaxy_info:
  author: Cassiano Ricardo Filho
  description: Receita que configura dinamicamente um container docker com um daemon bacula-sd.
  company: POP-PR  
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 2   