---
# handlers file for bacula-storage
  - name: restart_bacula
    service: name="{{item.name}}" state=restarted  
    loop:
      - {name: bacula-sd}
      - {name: bacula-fd}
    
  - name: reload_bacula_dir
    shell: docker exec {{ director_container_name }} "./etc/bacula/scripts/reloadConsoleHandler.sh"
    run_once: true
    delegate_to: "{{ director_address }}"